name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcairo2-dev pkg-config

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel build twine pandas numpy scipy scikit-learn umap-learn rdkit ray[default] plotly matplotlib seaborn matplotlib-venn upsetplot cloudpickle tqdm psutil pycairo requests pyyaml typing-extensions

      - name: Run tests
        run: pytest